services:
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - 6379:6379
        volumes:
            - ./docker_services_data/redis_data:/data
            - ./config/redis.conf:/redis.conf
        command: redis-server /redis.conf
