services:
    redis:
        image: redis:latest
        container_name: redis_go_redis
        ports:
            - 6379:6379
        volumes:
            - ./docker_services_data/redis_data:/data
            - ./config/redis.conf:/redis.conf
        command: redis-server /redis.conf
    k6:
        image: loadimpact/k6
        container_name: k6_go_redis
        environment:
            - K6_OUT=influxdb=http://influxdb:8086/k6_load_test
        extra_hosts:
            - host.docker.internal:host-gateway
        volumes:
            - ./scripts:/scripts
    influxdb:
        image: influxdb:1.8.10
        container_name: influxdb_go_redis
        environment:
            - INFLUXDB_DB=k6_load_test
            - INFLUXDB_HTTP_MAX_BODY_SIZE=0
        ports:
            - 8086:8086
        volumes:
            - ./docker_services_data/influxdb:/var/lib/influxdb
    grafana:
        image: grafana/grafana
        container_name: grafana
        environment:
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
        ports:
            - 3000:3000
        volumes:
            - ./docker_services_data/grafana:/var/lib/grafana
