services:
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - 6379:6379
        volumes:
            - ./docker_services_data/redis_data:/data
            - ./config/redis.conf:/redis.conf
        command: redis-server /redis.conf
    k6:
        image: loadimpact/k6
        container_name: k6
        extra_hosts:
            - host.docker.internal:host-gateway
        volumes:
            - ./scripts:/scripts
